### PR TITLE
Fixed "Last seen" variable

### PR DESCRIPTION
**Pull request by jonatascm**
Hello guys!
I found I bug that my messages won't loading for first time and I found there is an error when loading the customer infos.
I debugged and found a wrong variable name, maybe it changed between versions but not fixed in this lib.

I'm making this PR to fix this variable, the main fix was change the variable name:
`lastSeen` to `lastSeenAt`
`last_seen` to `last_seen_at`

### CODE REVIEW

**Comment by aguilaair** [comment]
Thanks for this! I'll take a look ASAP

**Comment by aguilaair** [comment]
This looks great! Thanks!

**Comment by aguilaair** [comment]
I've been investigating, and at some point papercups changed from `last_seen` to `last_seen_at`

**Comment by aguilaair** [comment]
@reichert621 @cheeseblubber in the future could you notify me of API changes? Just so that I can update the lib before the deprecation

**Comment by reichert621** [comment]
for sure! sorry bout that 😅

**Pull request merged**
