### PR TITLE
2.0.0 - Native Dart Widget

### PR DESCRIPTION
**Pull request by aguilaair**
This is a complete rewrite of the library, with native chat support, meaning it is faster and with many more customization possibilities, including:

- Dark mode
- Gradient support
- Immediate loading of chat widget
- Exact time on click
- Minimal libraries
- Performant

Additionally, This enables many more modifications tailored to apps that the web version can't (for future version, will not be included in 2.0.0):

- Proactive messaging, in other words new messages will appear ovelayed on the user. The user must have initiated a conversation before, we can't do this without a conversation ID, that conversation ID can then be listened for if initialized on app boot.
- Local, encrypted chat sessions  -- We will be using Hive for this. Stops the few seconds of requesting data and loading it up. Will still be requested and updated, but should first load the local verision for speed
- Multiple conversations -- Similar to what Intercom does
- Image upload -- Should be relatively simple once the logic is ready on the Papercups backend
- Even deeper theming -- Maybe multiple, completely different styles?
- Replying to certain conversations by sliding like in Telegram/Whatsapp? we could just use the quote block feature from markdown for this.

### CODE REVIEW

**Comment by aguilaair** [comment]
We're putting the finishing touches to this version, @Fiyiin is working on the tests and I'm working on the docs, once that is complete I think we're ready to merge!

Hopefully is 1-2 weeks.

**Comment by aguilaair** [comment]
I feel like this is at a pretty good stage, except for the few missing test. What do you think @Fiyiin?

**Comment by reichert621** [comment]
@aguilaair do you mind including more screenshots of the various states of this? just want some comparisons with the existing design :)

**Comment by aguilaair** [comment]
@reichert621 Yes!

image

**Pull request merged**
